1.  

<!-- -->

    ##                       Diabetic Complications-Present
    ## Diabetic Control-Good                              3
    ## Diabetic Control-Poor                              4
    ##                       Diabetic Complications-Absent
    ## Diabetic Control-Good                             7
    ## Diabetic Control-Poor                             2

    ##                       Diabetic Complications-Present
    ## Diabetic Control-Good                      0.3000000
    ## Diabetic Control-Poor                      0.6666667
    ##                       Diabetic Complications-Absent
    ## Diabetic Control-Good                     0.7000000
    ## Diabetic Control-Poor                     0.3333333

The patients who has good diabetic control only 30% of them have
diabetic complication present. Those patients who does not have good
diabetic control has 66.7% diabetic complication control present.

1.  

<!-- -->

    ## 
    ##  Fisher's Exact Test for Count Data
    ## 
    ## data:  test
    ## p-value = 0.3024
    ## alternative hypothesis: true odds ratio is not equal to 1
    ## 95 percent confidence interval:
    ##  0.0137305 2.7634624
    ## sample estimates:
    ## odds ratio 
    ##  0.2384682

The p-value is 0.3024 which is greater than 0.05. Therefore the
difference between two groups are not statistically different as it can
happen by chance.

1.  The patients are arranged into categories, but it has a very small
    samples. In addition, it is okay to have some expected counts less
    than 5, provided none are less than 1, and at least 80% of the
    expected counts are equal to or greater than 5.
